### ISSUE TITLE
Zly format XSD

### ISSUE THREAD

**Issue by simonharvan** [simonharvan/sipvs#2]
- Moze byt aj 0 pocet pasazierov.
- Treba pridat vygenerovane id formulara
- Mozno by sa hodilo dat na niektore z tych fieldov mozne volby (ako je pri tom selecte vo forme)

**Comment by mariusrak** [comment]
Čo znamená "Treba pridat vygenerovane id formulara" ? Veď je tam atribút ID a aj má hodnotu v XMLku

**Comment by simonharvan** [comment]
To znamena z Javy generovat, to tam hodim aj ja.
