### ISSUE TITLE
Zmergovanie a vyriesenie problemov v projekte 

### ISSUE THREAD

**Issue by simonharvan** [simonharvan/sipvs#3]
Aktualne nejde projekt. Treba vymazat .idea, output files a mergnut, tak aby sla validacia aj ukladanie XML.

**Comment by mariusrak** [comment]
Tuším, že pracovať na ostatných by sme mali až keď merge budú spravené aby sme nepridávali ďalšiu robotu, však?

**Comment by mariusrak** [comment]
Ako sa darí? Zmergované?

**Comment by simonharvan** [comment]
Z casti, este cakam na @kyjovcan, lebo mal nejaky kod nepushnuty.

**Comment by simonharvan** [comment]
Okej, uz je to tam vsetko.
